name: .Net Core

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .Net
      uses: actions/setup-dotnet@1.2.0
      with: 
        dotnet-version: 3.1.000
      if: matrix.os == 'maxOS.latest' || matrix.os == 'ubuntu-latest'
    - name: Restore Dependencies
      run: cd netcore_all_src; dotnet restore
    - name: Build
      run: cd netcore_all_src; dotnet build --configuration Release
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: DevBuild
        path: netcore_all_src/bin/Release